INSERT INTO Items (ItemName)
VALUES
    ('Coral Coast Arch'),
    ('White Rose Metal Arch'),
    ('Birch Pole Arch'),
    ('Lacy Crystal Serving Set'),
    ('Personalized Silver Serving Set'),
    ('Personalized Serving Set'),
    ('Always And Forever Aisle Runner'),
    ('Lace And Rayon Aisle Runenr'),
    ('Two Become One Aisle Runner'),
    ('100 Ct. Peruvian Lily'),
    ('12 Ct. Red Roses'),
    ('12 Ct. Multicolor Roses'),
    ('12 Ct. Black Roses'),
    ('Trumpet Mermaid Bead/Lace Dress with Train'),
    ('Gauze Scoop Mermaid with Train'),
    ('Vera Wang Embroidered Wedding Gown'),
    ('Amateur Officiant'),
    ('Part-time Officiant'),
    ('Professional Officiant'),
    ('Senior Officiant'),
    ('Senior Officiant Plus'),
    ('Basic Engagement Shoot'),
    ('Basic Engagement Shoot and Wedding Shoot'),
    ('Wedding Photo Shoot Plus'),
    ('Advanced Wedding Photo Shoot'),
    ('Advanced Wedding Photo Shoot Plus'),
    ('Two Teir Cake'),
    ('Three Teir Cake'),
    ('Three Teir Cake Customized'),
    ('Four Teir Cake'),
    ('Custom Four Teir Cake');